[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.18.4"
ic-cdk-macros = "0.18.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
candid = "0.10.4"
num-traits = "0.2"